const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let projects=[],media=[],settings={},categories=[],categoryDraft=[],findingDraft=[],stepDraft=[];
let beforeRef='',afterRef='',followUpRef='',uid=0;
const newUid=()=>`m${++uid}`;
async function req(url,opt){const r=await fetch(url,opt),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'요청 실패');return d}
const json=(method,body)=>({method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
function app(ok){$('#loginView').style.display=ok?'none':'block';$('#app').style.display=ok?'block':'none';if(ok)load()}
function view(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav-button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='reviews')reviews();if(id==='categories')renderCategories()}
$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{await req('/api/login',json('POST',{password:$('#password').value}));app(true)}catch(x){$('#loginMessage').textContent=x.message}};
$('#logout').onclick=async()=>{await req('/api/logout',{method:'POST'}).catch(()=>{});app(false)};
req('/api/login').then(x=>app(x.authenticated)).catch(()=>app(false));
async function load(){const [p,s,c]=await Promise.all([req('/api/projects'),req('/api/settings'),req('/api/categories')]);projects=p.projects||[];settings=s;categories=c.categories||[];categoryDraft=categories.map(name=>({original:name,name}));categoryOptions();list();stats();setting();renderCategories()}
function categoryOptions(selected){$('#category').innerHTML=categories.map(name=>`<option value="${esc(name)}">${esc(name)}</option>`).join('');if(selected&&categories.includes(selected))$('#category').value=selected}
function stats(){$('#totalCount').textContent=projects.length;$('#publishedCount').textContent=projects.filter(x=>x.status!=='draft').length;$('#featuredCount').textContent=projects.filter(x=>x.featured&&x.status!=='draft').length}
function list(){$('#projectList').innerHTML=projects.map(x=>`<article class="row"><img class="thumb" src="${esc(x.coverImage||x.images?.[0]||'')}"><div><h3>${esc(x.title)}</h3><div class="row-meta">${esc(x.category)} · ${esc(x.region)} · ${x.status==='draft'?'비공개':'게시'}${x.featured?' · HOME 노출':''}${x.hero?' · HOME 대표':''}</div></div><div class="actions"><button class="secondary" onclick="edit('${x.id}')">수정</button><button class="danger" onclick="del('${x.id}')">삭제</button></div></article>`).join('')||'<div class="placeholder">등록된 시공사례가 없습니다.</div>'}
$('#newProject').onclick=()=>editor();
function editor(x={}){
  $('#projectForm').reset();
  for(const k of ['projectId','siteId','workDate','title','region','description','details','story','result','review'])$('#'+k).value=x[k==='projectId'?'id':k]||'';
  $('#followUpPeriod').value=x.followUp?.period||'';$('#followUpContent').value=x.followUp?.content||'';
  categoryOptions(x.category||categories[0]);$('#reviewVisible').checked=!!x.reviewVisible;$('#featured').checked=!!x.featured;$('#hero').checked=!!x.hero;$('#published').checked=x.status!=='draft';
  media=(x.images||[]).map(path=>({uid:newUid(),path,existing:true,cover:path===(x.coverImage||x.images?.[0])}));
  const refFor=path=>media.find(m=>m.path===path)?.uid||'';
  beforeRef=refFor(x.beforeImage);afterRef=refFor(x.afterImage);followUpRef=refFor(x.followUp?.image);
  findingDraft=Array.isArray(x.findings)?[...x.findings]:[];
  stepDraft=(Array.isArray(x.processSteps)?x.processSteps:[]).map(step=>({title:step.title||'',description:step.description||'',images:(step.images||[]).map(refFor).filter(Boolean)}));
  $('#editorTitle').textContent=x.id?'시공사례 수정':'새 시공사례';renderMedia();renderFindings();renderSteps();view('editor')
}
window.edit=id=>editor(projects.find(x=>x.id===id));
window.del=async id=>{if(confirm('삭제할까요?')){await req('/api/projects',json('DELETE',{id}));await load()}};
$('#photos').onchange=e=>{media.push(...[...e.target.files].map(file=>({uid:newUid(),file,url:URL.createObjectURL(file)})));media=media.slice(0,20);if(!media.some(x=>x.cover)&&media[0])media[0].cover=true;e.target.value='';renderMedia();renderImageSelects();renderSteps()};
function renderMedia(){$('#previews').innerHTML='';media.forEach((m,i)=>{const d=document.createElement('div');d.className='preview'+(m.cover?' selected':'');d.innerHTML=`<img src="${esc(m.existing?m.path:m.url)}" alt="시공사진 미리보기"><button type="button" class="remove" aria-label="사진 삭제">×</button><button type="button" class="cover">${m.cover?'★ 대표':'☆ 대표'}</button>`;d.querySelector('.remove').onclick=()=>{const removed=media.splice(i,1)[0];beforeRef=beforeRef===removed.uid?'':beforeRef;afterRef=afterRef===removed.uid?'':afterRef;followUpRef=followUpRef===removed.uid?'':followUpRef;stepDraft.forEach(s=>s.images=s.images.filter(id=>id!==removed.uid));if(!media.some(x=>x.cover)&&media[0])media[0].cover=true;renderMedia();renderImageSelects();renderSteps()};d.querySelector('.cover').onclick=()=>{media.forEach(x=>x.cover=false);m.cover=true;renderMedia()};$('#previews').append(d)});renderImageSelects()}
function imageLabel(m,i){return `${i+1}. ${m.existing?(m.path.split('/').pop()||'기존 사진'):(m.file?.name||'새 사진')}`}
function imageOptions(selected,empty='선택하지 않음'){return `<option value="">${empty}</option>`+media.map((m,i)=>`<option value="${m.uid}" ${m.uid===selected?'selected':''}>${esc(imageLabel(m,i))}</option>`).join('')}
function renderImageSelects(){for(const [id,value,set] of [['beforeImage',beforeRef,v=>beforeRef=v],['afterImage',afterRef,v=>afterRef=v],['followUpImage',followUpRef,v=>followUpRef=v]]){const el=$('#'+id);if(!el)continue;el.innerHTML=imageOptions(value);el.onchange=()=>set(el.value)}}
function renderFindings(){$('#findingRows').innerHTML=findingDraft.map((text,i)=>`<div class="repeat-row"><input value="${esc(text)}" maxlength="300" data-finding="${i}" placeholder="예: 창호와 외벽 접합부"><div class="inline-actions"><button class="small" type="button" data-fup="${i}">↑</button><button class="small" type="button" data-fdown="${i}">↓</button><button class="danger small" type="button" data-fremove="${i}">삭제</button></div></div>`).join('');$$('[data-finding]').forEach(el=>el.oninput=()=>findingDraft[+el.dataset.finding]=el.value);$$('[data-fremove]').forEach(el=>el.onclick=()=>{findingDraft.splice(+el.dataset.fremove,1);renderFindings()});$$('[data-fup]').forEach(el=>el.onclick=()=>move(findingDraft,+el.dataset.fup,-1,renderFindings));$$('[data-fdown]').forEach(el=>el.onclick=()=>move(findingDraft,+el.dataset.fdown,1,renderFindings))}
$('#addFinding').onclick=()=>{findingDraft.push('');renderFindings();$$('[data-finding]').at(-1)?.focus()};
function move(list,i,delta,render){const j=i+delta;if(j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];render()}
function renderSteps(){$('#stepRows').innerHTML=stepDraft.map((step,i)=>`<article class="record-block"><div class="record-head"><h3>${String(i+1).padStart(2,'0')} / 작업 단계</h3><div class="inline-actions"><button class="small" type="button" data-sup="${i}">↑</button><button class="small" type="button" data-sdown="${i}">↓</button><button class="danger small" type="button" data-sremove="${i}">삭제</button></div></div><div class="record-grid"><div><label>단계 제목</label><input data-stitle="${i}" maxlength="120" value="${esc(step.title)}"></div><div><label>단계 사진 (여러 장 선택 가능)</label><select data-simages="${i}" multiple>${media.map((m,n)=>`<option value="${m.uid}" ${step.images.includes(m.uid)?'selected':''}>${esc(imageLabel(m,n))}</option>`).join('')}</select></div><div style="grid-column:1/-1"><label>간단한 설명</label><textarea data-sdesc="${i}" maxlength="2000">${esc(step.description)}</textarea></div></div></article>`).join('');$$('[data-stitle]').forEach(el=>el.oninput=()=>stepDraft[+el.dataset.stitle].title=el.value);$$('[data-sdesc]').forEach(el=>el.oninput=()=>stepDraft[+el.dataset.sdesc].description=el.value);$$('[data-simages]').forEach(el=>el.onchange=()=>stepDraft[+el.dataset.simages].images=[...el.selectedOptions].map(o=>o.value));$$('[data-sremove]').forEach(el=>el.onclick=()=>{stepDraft.splice(+el.dataset.sremove,1);renderSteps()});$$('[data-sup]').forEach(el=>el.onclick=()=>move(stepDraft,+el.dataset.sup,-1,renderSteps));$$('[data-sdown]').forEach(el=>el.onclick=()=>move(stepDraft,+el.dataset.sdown,1,renderSteps))}
$('#addStep').onclick=()=>{stepDraft.push({title:'',description:'',images:[]});renderSteps();$$('[data-stitle]').at(-1)?.focus()};
async function optimize(file){const b=await createImageBitmap(file),s=Math.min(1,1600/Math.max(b.width,b.height)),c=document.createElement('canvas');c.width=Math.round(b.width*s);c.height=Math.round(b.height*s);c.getContext('2d').drawImage(b,0,0,c.width,c.height);b.close();let q=.84,o;do{o=await new Promise(r=>c.toBlob(r,'image/jpeg',q));q-=.1}while(o.size>1e6&&q>=.44);return o}
const b64=blob=>new Promise(ok=>{const r=new FileReader;r.onload=()=>ok(r.result.split(',')[1]);r.readAsDataURL(blob)});
$('#projectForm').onsubmit=async e=>{e.preventDefault();const msg=$('#projectMessage'),btn=$('#saveProject');if(!media.length)return msg.textContent='사진을 선택해 주세요.';btn.disabled=true;try{const images=[];for(let i=0;i<media.length;i++){const m=media[i];if(m.existing){m.savedPath=m.path;images.push(m.path)}else{msg.textContent=`사진 업로드 중 ${i+1}/${media.length}`;const uploaded=await req('/api/upload',json('POST',{content:await b64(await optimize(m.file)),mimeType:'image/jpeg'}));m.savedPath='/'+uploaded.path;images.push(uploaded)}}const pathFor=id=>media.find(m=>m.uid===id)?.savedPath||'';const body={};for(const k of ['category','siteId','workDate','title','region','description','details','story','result','review'])body[k]=$('#'+k).value;Object.assign(body,{id:$('#projectId').value,findings:findingDraft.map(v=>v.trim()).filter(Boolean),processSteps:stepDraft.map(s=>({title:s.title,description:s.description,images:s.images.map(pathFor).filter(Boolean)})),beforeImage:pathFor(beforeRef),afterImage:pathFor(afterRef),followUp:{period:$('#followUpPeriod').value,content:$('#followUpContent').value,image:pathFor(followUpRef)},reviewVisible:$('#reviewVisible').checked,featured:$('#featured').checked,hero:$('#hero').checked,status:$('#published').checked?'published':'draft',images,coverIndex:media.findIndex(x=>x.cover)});await req('/api/projects',json(body.id?'PUT':'POST',body));msg.className='message success';msg.textContent='저장되었습니다.';await load();setTimeout(()=>view('projects'),700)}catch(x){msg.className='message error';msg.textContent=x.message}finally{btn.disabled=false}};
function renderCategories(){$('#categoryRows').innerHTML=categoryDraft.map((row,i)=>{const locked=row.original==='인조대리석 문지방';return `<div class="category-row"><input value="${esc(row.name)}" maxlength="40" data-index="${i}" aria-label="카테고리 이름" ${locked?'disabled title="전문페이지 연동 카테고리"':''}><button class="danger" type="button" data-remove="${i}" ${locked?'disabled':''}>삭제</button></div>`}).join('');$$('#categoryRows input').forEach(input=>input.oninput=()=>categoryDraft[+input.dataset.index].name=input.value);$$('[data-remove]').forEach(button=>button.onclick=()=>{categoryDraft.splice(+button.dataset.remove,1);renderCategories()})}
$('#addCategory').onclick=()=>{categoryDraft.push({original:'',name:''});renderCategories();$('#categoryRows input:last-of-type')?.focus()};
$('#categoryForm').onsubmit=async e=>{e.preventDefault();const msg=$('#categoryMessage');try{const data=await req('/api/categories',json('PUT',{categories:categoryDraft}));categories=data.categories;categoryDraft=categories.map(name=>({original:name,name}));categoryOptions();renderCategories();msg.className='message success';msg.textContent='저장되었습니다. HOME과 WORK에도 자동 반영됩니다.';await load()}catch(x){msg.className='message error';msg.textContent=x.message}};
function reviews(){$('#reviewList').innerHTML=projects.filter(x=>x.review).map(x=>`<article class="row"><img class="thumb" src="${esc(x.coverImage||x.images?.[0])}"><div><h3>${esc(x.title)}</h3><div class="row-meta">${x.reviewVisible?'공개':'비공개'} · ${esc(x.review)}</div></div><button class="secondary" onclick="edit('${x.id}')">수정</button></article>`).join('')||'<div class="placeholder">후기가 없습니다.</div>'}
function setting(){$('#ledgerUrl').value=settings.ledgerUrl||'';$('#ledgerLink').style.display=settings.ledgerUrl?'inline-block':'none';$('#ledgerEmpty').style.display=settings.ledgerUrl?'none':'block';if(settings.ledgerUrl){$('#ledgerLink').href=settings.ledgerUrl;$('#ledgerLink').target='_blank';$('#ledgerLink').rel='noopener noreferrer'}}
$('#settingsForm').onsubmit=async e=>{e.preventDefault();try{settings=await req('/api/settings',json('PUT',{ledgerUrl:$('#ledgerUrl').value}));setting();$('#settingsMessage').textContent='저장되었습니다.'}catch(x){$('#settingsMessage').textContent=x.message}};
